export const ETSY_PRIMARY_COLOURS = [
  { value: 'beige', label: 'Beige' },
  { value: 'black', label: 'Black' },
  { value: 'blue', label: 'Blue' },
  { value: 'bronze', label: 'Bronze' },
  { value: 'brown', label: 'Brown' },
  { value: 'clear', label: 'Clear' },
  { value: 'copper', label: 'Copper' },
  { value: 'gold', label: 'Gold' },
  { value: 'gray', label: 'Grey', etsyLabel: 'Gray' },
  { value: 'green', label: 'Green' },
  { value: 'orange', label: 'Orange' },
  { value: 'pink', label: 'Pink' },
  { value: 'purple', label: 'Purple' },
  { value: 'rainbow', label: 'Rainbow' },
  { value: 'red', label: 'Red' },
  { value: 'rose-gold', label: 'Rose gold' },
  { value: 'silver', label: 'Silver' },
  { value: 'white', label: 'White' },
  { value: 'yellow', label: 'Yellow' },
] as const;
